api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "cart-checkout-validation-gwp"
type = "function"
uid = "65ccd3aa-f8c0-7948-6f2e-0756764c20c27b966665"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
